### ISSUE TITLE
Some tags incorrectly translated between flac and mp3

### ISSUE THREAD

**Issue by zoof** [smxi/acxi#11]
After converting my entire digital music library from flac to mp3, I have found that the tags are mis-translated with some frequency.  My music player, Clementine, correctly displays the track number, title, artist and album for the flac file but for the mp3 file, the tag information appears to have been pulled from the filename:  no track number, title is correct, artist is the track number and the album is folder name.

I am running Debian Bullseye with Gnome.

**Comment by smxi** [comment]
The tag information is not pulled from the file name. I suspect as first guess your flacs are not tagged correctly, and that they are the source of the bad tags. I've seen tags that are based on the file name, those are created by various poor quality tagging tools.

As a Debian free software and operating system user, you might look at dumping mp3, which is 100% non free. Opus is better, unless you have an apple iphone of course, or a tesla, neither of which as far as I know support opus.

However, to check your tags, and again, my first guess is that your flacs are tagged incorrectly, we want to verify this:

Taken any mp3 that shows this behavior, and run this command on the source flac for it:

`metaflac --list --block-number 0,1 [file].flac`

This will show non-ambiguously what the tagging is.

To see the actual tagging data on the mp3 file do:

`ffprobe [file].mp3`

Paste both outputs here. My guess it will quickly grow obvious what the actual cause is.

Note that acxi does not make up or fake tagging, it uses only what is there. Also, I use clementine as well, and if it is showing the file name, that means that there is no tagging information.

Because mp3 is worst in class for consistent tagging etc, acxi only supports the following basic mp3 tags:

`@tags = ('ARTIST', 'ALBUM', 'TITLE','GENRE', 'DATE', 'TRACKNUMBER', 	'TRACKTOTAL','DISKNUMBER','DISKTOTAL');`

**Comment by zoof** [comment]
Here is an interesting case.  Everything else on this CD has tags translated to MP3 correctly but this one is missing.
```
$ metaflac --list --block-number 0,1 08\ -\ The\ Midnight\ Special.flac 
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4608 samples
  maximum blocksize: 4608 samples
  minimum framesize: 5580 bytes
  maximum framesize: 13902 bytes
  sample_rate: 44100 Hz
  channels: 2
  bits-per-sample: 16
  total samples: 11178822
  MD5 signature: cf747fa5ca7bf512c7c5b83459b8032d
METADATA block #1
  type: 3 (SEEKTABLE)
  is last: false
  length: 450
  seek points: 25
    point 0: sample_number=0, stream_offset=0, frame_samples=4608
    point 1: sample_number=446976, stream_offset=843100, frame_samples=4608
    point 2: sample_number=893952, stream_offset=1671286, frame_samples=4608
    point 3: sample_number=1340928, stream_offset=2526145, frame_samples=4608
    point 4: sample_number=1787904, stream_offset=3345105, frame_samples=4608
    point 5: sample_number=2234880, stream_offset=4192221, frame_samples=4608
    point 6: sample_number=2681856, stream_offset=5145404, frame_samples=4608
    point 7: sample_number=3128832, stream_offset=6158016, frame_samples=4608
    point 8: sample_number=3575808, stream_offset=7264024, frame_samples=4608
    point 9: sample_number=4022784, stream_offset=8327348, frame_samples=4608
    point 10: sample_number=4469760, stream_offset=9398333, frame_samples=4608
    point 11: sample_number=4916736, stream_offset=10465679, frame_samples=4608
    point 12: sample_number=5363712, stream_offset=11563511, frame_samples=4608
    point 13: sample_number=5810688, stream_offset=12659655, frame_samples=4608
    point 14: sample_number=6257664, stream_offset=13754459, frame_samples=4608
    point 15: sample_number=6704640, stream_offset=14817249, frame_samples=4608
    point 16: sample_number=7151616, stream_offset=15886095, frame_samples=4608
    point 17: sample_number=7598592, stream_offset=16949143, frame_samples=4608
    point 18: sample_number=8045568, stream_offset=18043469, frame_samples=4608
    point 19: sample_number=8492544, stream_offset=19145342, frame_samples=4608
    point 20: sample_number=8939520, stream_offset=20238563, frame_samples=4608
    point 21: sample_number=9386496, stream_offset=21249254, frame_samples=4608
    point 22: sample_number=9833472, stream_offset=22237741, frame_samples=4608
    point 23: sample_number=10280448, stream_offset=23338489, frame_samples=4608
    point 24: sample_number=10727424, stream_offset=24420628, frame_samples=4608
```
```
$ ffprobe 08\ -\ The\ Midnight\ Special.mp3 
ffprobe version 4.1.8-0+deb10u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version=0+deb10u1 --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabi --incdir=/usr/include/arm-linux-gnueabi --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mp3, from '08 - The Midnight Special.mp3':
  Metadata:
    encoder         : LAME 32bits version 3.100 (http://lame.sf.net)
    TLEN            : 253488
  Duration: 00:04:13.52, start: 0.025057, bitrate: 170 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 170 kb/s
    Metadata:
      encoder         : LAME3.100
    Side data:
      replaygain: track gain - -3.400000, track peak - unknown, album gain - unknown, album peak - unknown,
```

**Comment by smxi** [comment]
Sorry, probably safest to just run: metaflac --list  08\ -\ The\ Midnight\ Special.flac 

I was assuming tag data would be in the first 2 blocks, just checked, it can be in the 3d, as in:
metaflac --list --block-number 0,1,2 08\ -\ The\ Midnight\ Special.flac 
or
metaflac --list  08\ -\ The\ Midnight\ Special.flac 
which will just show all the metadata.

I believe that clementine behavior is the default for untagged, it will just use the basic rule that the directory containging the file is the album name, and the directory containing that directory is the artist name, I think that's how it works, I forget.

Sounds like your tagging software had a glitch, I've always either made my own, more so now that acxi works really well for that, way faster than anything else, and far more accurate since it's always based on the data I give it, or used abcde, which if set to grab tags from online db usually does ok. Not as well as when freedb was still online, but not bad. Otherwise I have to type them in manually before abcde runs, that's for cds, nothing else of course.

If the flac was tagged and the mp3 was not, that would be an odd situation but a possible acxi error.

Found and fixed the m4a issue. Note that m4a tags don't require any odd hacks to transfer, they 'just work', same as opus, ogg. AAC doesn't support metadata like tags, and mp3 has to be done using Lame if I remember right.

The only lossy output format that natively transfers embedded cover images is opus, that never worked for ogg, requires a super convoluted hack, and I never bothered even trying with mp3.

Some players will use a cover.jpg if included in the main audio file directory, but that's hit and miss.

**Comment by zoof** [comment]
Here it the updated `metaflac` info.  I'm happy to build my own tagging software -- what do you use?

```
$ metaflac --list --block-number 0,1,2 08\ -\ The\ Midnight\ Special.flac
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4608 samples
  maximum blocksize: 4608 samples
  minimum framesize: 5580 bytes
  maximum framesize: 13902 bytes
  sample_rate: 44100 Hz
  channels: 2
  bits-per-sample: 16
  total samples: 11178822
  MD5 signature: cf747fa5ca7bf512c7c5b83459b8032d
METADATA block #1
  type: 3 (SEEKTABLE)
  is last: false
  length: 450
  seek points: 25
    point 0: sample_number=0, stream_offset=0, frame_samples=4608
    point 1: sample_number=446976, stream_offset=843100, frame_samples=4608
    point 2: sample_number=893952, stream_offset=1671286, frame_samples=4608
    point 3: sample_number=1340928, stream_offset=2526145, frame_samples=4608
    point 4: sample_number=1787904, stream_offset=3345105, frame_samples=4608
    point 5: sample_number=2234880, stream_offset=4192221, frame_samples=4608
    point 6: sample_number=2681856, stream_offset=5145404, frame_samples=4608
    point 7: sample_number=3128832, stream_offset=6158016, frame_samples=4608
    point 8: sample_number=3575808, stream_offset=7264024, frame_samples=4608
    point 9: sample_number=4022784, stream_offset=8327348, frame_samples=4608
    point 10: sample_number=4469760, stream_offset=9398333, frame_samples=4608
    point 11: sample_number=4916736, stream_offset=10465679, frame_samples=4608
    point 12: sample_number=5363712, stream_offset=11563511, frame_samples=4608
    point 13: sample_number=5810688, stream_offset=12659655, frame_samples=4608
    point 14: sample_number=6257664, stream_offset=13754459, frame_samples=4608
    point 15: sample_number=6704640, stream_offset=14817249, frame_samples=4608
    point 16: sample_number=7151616, stream_offset=15886095, frame_samples=4608
    point 17: sample_number=7598592, stream_offset=16949143, frame_samples=4608
    point 18: sample_number=8045568, stream_offset=18043469, frame_samples=4608
    point 19: sample_number=8492544, stream_offset=19145342, frame_samples=4608
    point 20: sample_number=8939520, stream_offset=20238563, frame_samples=4608
    point 21: sample_number=9386496, stream_offset=21249254, frame_samples=4608
    point 22: sample_number=9833472, stream_offset=22237741, frame_samples=4608
    point 23: sample_number=10280448, stream_offset=23338489, frame_samples=4608
    point 24: sample_number=10727424, stream_offset=24420628, frame_samples=4608
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 205
  vendor string: reference libFLAC 1.1.2 20050205
  comments: 7
    comment[0]: album=Willie & The Poor Boys
    comment[1]: title=The Midnight Special
    comment[2]: artist=Creedence Clearwater Revival
    comment[3]: genre=Rock
    comment[4]: date=1969
    comment[5]: tracknumber=8/10
    comment[6]: discnumber=/0
```

**Comment by smxi** [comment]
Tagging is wrong, track number  tag is an integer. Disc number is either unset or an integer. Disc number shouldn't in general be used unless > 1 disks in set because can lead to weird output. I have no idea what happens in mp3

That's going to cause mp3 tags to fail probably, because acxi creates the proper mp3 syntax for disk/track numbers out of the correctly done flac tags, it doesn't, and won't, try to correct user tags. 

You've confused the mp3 syntax for track/disk numbers with the flac/vorbis syntax:

```
TRACKNUMBER == integer
TRACKTOTAL == integer
DISKNUMBER = unset or an integer
DISKTOTAL = an integer
```

mp3 does this, of course, badly, and those are converted to:

`--tn "TRACKNUMBER/TRACKTOTAL "`

and if DISKNUMBER is defined and > 0:
`--tv "DISKNUMBER/DISKTOTAL"`

Media players have poor support for 'date', which is actually something like 1969-10-23, YEAR is for year, most media players support year.

Basically, mp3 tags are broken and wrong, and all other tags work fine and interact fine, so NEVER ever use mp3 tagging syntax in any other tag format, you have to map correct tag formats TO mp3 when creating mp3.

There are many reasons I don't touch mp3 ever, and this is one of them. The fact they couldn't even create a consistent tagging format across mp3 versions is another. The fact mp3 sounds like total shit when compared to similar bit rate ogg, opus, aac, or m4a, is of course the main one.

Tagging is very complicated, it is massively hampered by the total failure of the various groups, in particular, the ziph.org group, to create locked down always there tag syntax, instead, as you see from your above, there's no such thing as a tag in vorbis/flac etc metadata, it's a 'comment', which is then used as a tag by media players who will use their restricted subset of generally always supported tag names to show or not show the tag data in the player.

To get stable reliable cross media player tagging done required a huge amount of research. Cover image embedding is even harder due to some strange decisions made in terms of how to handle embedded images. Suffice it to say xiph.org did not follow their own written specifications for image embedding, and also require a very specific process to remove and replace images, which took me ages to work out. Not for the faint hearted.

I use acxi exclusively now for tagging, it took a long time to get this feature to be as robust as it is now, still a few fine tunings added now and then. It's a power user feature, you have to learn how it works, and how to create tag seed info.txt files, the man page roughly outlines how to do it. Once the auto.tag file is created, which is a text file inxi uses to create the tags, you only ever need to edit that file to update the tags. acxi also supports updating individual tags, or tag sets, and updating tags in a block of artists or shows using file globbing (-g) which is very useful as well. But it's poweruser stuff, absolutely not made for newbies, nor will it ever be, there's plenty of not that well implemented tagging methods using guis out there for newbies.

Note that acxi tagging is written to not suck like most tagging software unfortunately does, and it was written keeping in mind the anemic media player tag support. So it only uses and creates a subset of possible tags, and even that subset is only supported natively by as far as I know 1 media player, quod libet, all the others do it wrong (multiple tags of the same tag are supposed to be put together, but most media players fail to do that, leading to supported features like > 1 artist, > 1 genre, > 1 comment, > 1 performer, only showing the first or last tag for that item.

It was also written to be so absurdly fast and efficient and accurate that I'd never think of wanting to use anything else again, and that goal was reached sometime this year, well, it was actually reached the first iteration, but the rough edges were more and more removed over the past year.

I can't walk you through the logic of tagging and media player support and image embedding, it was all very difficult, and far more random and convoluted than it should be.

**Comment by zoof** [comment]
Thank you for the extremely detailed explanation!

I'm using mp3 because my car does not take ogg but I should check and see if aac or m4a work though.

**Comment by smxi** [comment]
look into bluetooth for car and use your phone, that's what I do. With android and foobar2000 app, opus works perfectly. You can basically count on car audio systems to suck natively. Tesla supports ogg, and if someone poked Elon on twitter into adding opus, they would add that. Car companies that use outsourced 3rd party audio tools will not be very good in general.
