### ISSUE TITLE
Only create directories if tracks are transcoded

### ISSUE THREAD

**Issue by bitchkat** [smxi/acxi#4]
I exclude a number of directories when transferring audio files to a USB drive for my car.  None of these directories contain flac files but axci insists on recreating them on the destination directory whenever it runs.

Is it possible to have it only create directories if they contain source files that will be transcoded?  

I do clean it up afterwards with a semi-complicated rsync but it would be nice if they weren't created in the first place.

**Comment by smxi** [comment]
How do you exclude the directories? You are right, acxi is 'dumb' in that sense, it starts with the directories in your source, then recreates them in destination, then it goes to file types.

Since some people stick their audio files in sub-directories, it gets slightly trickier, though I did use a form of that detection for the new --checksum and --autotag options, those only run for example if there are flac files found in that directory.

**Comment by smxi** [comment]
To be clear, the main issue I had with acxi was having no way to know where the users had put their actual music files, is it the top level? one level down, two levels in, 3, 4? it can be all that, even deeper, so that's roughly why acxi generates all the directories it finds in your music collection folder.

**Comment by bitchkat** [comment]
For axci, what I'm looking for is to only create directories on the destination when you are going to transcode an audio file. Instead of creating missing directories up front,you would do it before transcoding.  Effectively, do the perl equivalent of "mkdir -p"  if the dest directory doesn't exist.

I use a combination of axci and rsync to sychronize my music directory to usb drive.  For artists that I will never listen to in the car, I just have a series of "--exclude=the_gordon_highlanders" style command line options to rsync.

**Comment by smxi** [comment]
ah, that's roughly how I do it too, acxi and rsync. Technically I could make a configuration value to take a comma separated list, or whatever characters are safe, I use ^^ to avoid possible appearance, that would basically form an excluded list, but if it's long, it would not be elegant. github's edit features are broken at the moment for me for issues, so I can't change what I write. I'd have to look at the logic carefully, there is an equivalent to mkdir -p which I'm already using in another context, so it's possible it could be done, but the loop works to copy over the copy types first, then the conversion processor runs. strictly speaking I don't have to have the directory making component if I carefully rewrite the copy and sync components. You can use an exclude file for rsync by the way, that's a lot cleaner and easier than using a series of --exclude options, it just reads the file and you just edit the file.

Note that in rsync, you can use --delete-excluded which will nuke anything you are excluding from the target usb stick directory. That's a little risky to use, so always use it with --dry-run / -n to make sure nothing disastrous happens the first time. That sounds like it would solve your issues as well.

**Comment by bitchkat** [comment]
This is my rsync command:
`rsync -avz --delete --delete-excluded --filter='merge transcoded.txt' --exclude=*.flac --exclude=shitty_artist1 --exclude=shitty_artist2 src dest`

transcoded.txt is dynamically created 

`    find . -name \*.flac | while read file
    do
        FILENAME=$(dirname "${file#./}")/$(basename "$file" .flac).ogg
        echo "protect $FILENAME"
    done >transcoded.txt
`

**Comment by smxi** [comment]
oh, I see what it's doing, acxi does that too, but in a different way and place in the logic. I never thought of using rsync in that way, that's clever. So why aren't the excluded directories being deleted? There's something I'm missing there.

**Comment by smxi** [comment]
I thought about this one, and realized the obvious logical paradox involved in checking directories for conversion file type, they would never exist if it was the first time it was run.

So I think that's not a direction that will work, plus altering the core looping logic for this is a real pain, and requires a ton of testing, so I believe the better option is to simply exclude a list, using a new config/global value option: 

`$EXCLUDES="badband1^^badband2^^boringband1^^whyisthisbandinmycollection2"; `

and so on.The length of the list wouldn't really matter, though there would be obvious practical limits, which means having as an alternate would be to support an exclude file, which would need a unique name, like acxi-excludes.txt so that acxi could test that value to determine if it's a file or a list, then it would split the list/file into an array, and test the initial filefind filenames against that list.

That would work pretty well. Since it would run in the sub wanted engine, not in specific locations, it would just block all sync actions on those files/folders. That logic is quite easy to do.

**Comment by bitchkat** [comment]
Checking directories for the conversion file type would occur on the source directory.  E.g.  Only create directories on the destination for source directories that contain flac files.  Here's a shell script that does what I'm thinking.  

`find . -name  \*.flac -exec dirname {}  \; | sort -u | while read dir
do
   if [ ! -d "$dir" ]
   then
       mkdir -p $dir
   fi
done`

With your current logic, you're surely doing something like
`find . -type d | while read $dir
do
   if [ ! -d "$dest/$dir" ]
   then
       mkdir "$dest/$dir" 
   fi
done`

What we're looking for is changing the test to something like

`if [ ! -d "$dest/$dir" && "$dest/$dir" has flac files ]
 then
    mkdir -p "$dest/$dir"
fi`

I think you could do this without a separate directory traversal just to create directories.  You could easily do this whenever you find a flac file.  Check if the dest directory exists and if not, create it.

Just need to figure out a simple way to check if the directory has any flac (or whatever the source type) is.

Instead of the EXCLUDES environment variable, how about just looking for a file named .acxi-exclude or something in the directory?  The only caveat with that is that it would be global instead of being configurable per acxi run -- maybe I want different artists in my car vs my phone?

**Comment by smxi** [comment]
That doesn't work, you're only looking at your case, many directories exist without flac files.

For example:

genre/band/record/art

There's multiple types being processed, flac is only one of them. All copy over file types are also there. 

And --exclude option would allow you to create multiple files, it would just  have to have a unique id acxi can test for, like acxi-excludes in the file name so acxi can know if it's looking at an inline list or a file. The file path would need to be absolute.

So you could do, say:

acxi -d music/phone-oggs --exclude='/home/me/music/excludes/acxi-excludes-phone.txt'

or something like that. That would be easy to implement and would not interfere with the logic.

The basic directory generation logic is heavily tested over years, and as I learned while creating some new directory generation logic, which I made mistakes on I think at least 5 times until I think I have it stable, it's a pain to alter heavily tested code that 100% certainly is working exactly as intended right now.

Note that it would make no difference if the directory creation occurred before or after the conversion step, since all that does is create all the directories that will be created anyway all at the same time, so the obvious place to filter is in file::find wanted sub, using an exclusion list. That doesn't interfere at all with existing logic, and would just be an optional filter that could be applied without altering existing logic.

**Comment by smxi** [comment]
EXLUDES would be an internal configuration value, set in acxi or in acxi config. It could include either a ^^ separated list of unique names (since it will be a regex match test, the name only needs to be the minimum string required to block that artist/recording). ^^ I use for user lists because it's pretty unusual for that combination to occur in user generated file names. In auto.tag, I used %:  because I wanted to make absolutely sure the user would not have that in the path or string value, then acxi splits on those characters. 

For a file, it would just be one regex check per line. File is obviously the easier way. --exclude and maybe also --exclude-append, which would just add to the existing excluded list, the same way --append does for copy types. Note that I believe that --clean would then also automatically remove anything not matched in the destination directory, since it's working off the same master list.

So that would work pretty well.

**Comment by smxi** [comment]
actually, I double checked (the directory creation part is really old), and yes, that creates directories not in destination that are in source. There are a few very fringe times when those directories will be extra and empty since no copy type extension or source audio type are in them, like if you are not transferring jpg artwork, but those times are quite unusual in most collections I think, and largely do not matter.

Plus as noted, I like seeing the list of directories it will be working on when it starts, I find that useful to me..

**Comment by smxi** [comment]
Hmm, no, clean would require some tweaks, but doable.

**Comment by smxi** [comment]
I take it back, --clean I do not believe would work as is with --exclude. It works at a more basic level of literal path to path comparison. Maybe I could squeeze in a test in wanted(), should work, I think, not positive. Takes testing.

**Comment by smxi** [comment]
Tentatively, tested and all seems groovy. $EXCLUDE in top options, takes list of ^^ separated string values, or a file name that contains $EXCLUDE_BASE in it. Default is acxi-excludes. 

Options to test: 
1. --exclude [list or file name]
2. --exclude-append [list]

EXCLUDE will either create an array based on the list, or create an array based on the lines of an exclude file. You provide the full path to the exclude file, and if desired, change the default name acxi will use to verify it's an exclude file and not a list. --exclude-append will append more items to the exclude array. 

Validations: if either ^^^^ or ending ^^ are found in EXCLUDE list, it will exit with error, since that would exclude an empty space, which is a mistake. If the EXCLUDE value is a file, and it does not exist, will exit as well. 

This was not too hard to implement, except the validation, which is always tedious since you have to assume users will do it wrong, so now there's a full exclude available.

Supports multiple exclude lists, say you are using default base of acxi-excludes, you could use:

Default: /home/you/music/excludes/acxi-excludes.txt
Alternate: /home/you/music/excludes/acxi-excludes-phone.txt
Alternate: /home/you/music/excludes/acxi-excludes-car.txt

and there you have it, exclude support. I did not have to touch the core logic at all, just added two more tests to the wanted process file/directory list.

Tested on --clean, works fine, tested on sync actions, works fine. 

Supports spaces in file names since the splits are either on lines, in files, or on ^^, in string lists.

And so on it goes, available now in 3.3.16, see if you can find bugs so i don't have to bump the version number to fix it. I'm loose with acxi version numbers since it doesn't have a huge user base, so I don't worry about making changes for 24 or so hours after a new version is done.

This was a pretty good idea, I think I've half thought of something like this but never really followed through on it. acxi has many such undone features, but far fewer now than 2 months or so ago.

**Comment by smxi** [comment]
Added config handling for EXCLUDE and EXCLUDE_BASE config file items.

Also finally handled --clean/CLEAN, now if --clean is used like so: --clean sync, it will proceed to sync after clean, but --clean alone will exit after clean. This had been a problem for a while, sometimes I only wanted to clean, other times I wanted it to proceed to sync, and CLEAN value in config always was supposed to always run clean before sync, but I had clean exit always, which broke that functionality.

So that's that, roughly, barring bugs or glitches.

**Comment by smxi** [comment]
Closing since no further response, and the issue is handled.
