### ISSUE TITLE
Not able to run acxi on CentOS 8

### ISSUE THREAD

**Issue by soerenschneider** [smxi/acxi#6]
I can't get the perl script running on CentOS 8. The following output is produced when trying run it (just tried git tag 3.3.19 and master at 87c798dfcffe8cdaa9225dad08bfab17e2c44803):

```
$ acxi
Initialization of state variables in list context currently forbidden at /usr/local/bin/acxi line 1528, near ");"
BEGIN not safe after errors--compilation aborted at /usr/local/bin/acxi line 1587.
``` 

Running `perl -v` yields
```
This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi
(with 51 registered patches, see perl -V for more detail)
```

The following packages related to perl are installed:

```
perl-Exporter-5.72-396.el8.noarch
perl-parent-0.237-1.el8.noarch
perl-Time-HiRes-1.9758-1.el8.x86_64
perl-Text-Tabs+Wrap-2013.0523-395.el8.noarch
perl-constant-1.33-396.el8.noarch
perl-Socket-2.027-3.el8.x86_64
perl-IO-Socket-IP-0.39-5.el8.noarch
perl-Digest-1.17-395.el8.noarch
perl-IO-Tty-1.12-11.el8.x86_64
perl-Pod-Escapes-1.07-395.el8.noarch
perl-Encode-2.97-3.el8.x86_64
perl-Pod-Usage-1.69-395.el8.noarch
perl-libnet-3.11-3.el8.noarch
perl-libs-5.26.3-416.el8.x86_64
perl-Scalar-List-Utils-1.49-2.el8.x86_64
perl-Text-ParseWords-3.30-395.el8.noarch
perl-Term-ANSIColor-4.06-396.el8.noarch
perl-Errno-1.28-416.el8.x86_64
perl-Unicode-Normalize-1.25-396.el8.x86_64
perl-PathTools-3.74-1.el8.x86_64
perl-threads-shared-1.58-2.el8.x86_64
perl-interpreter-5.26.3-416.el8.x86_64
perl-IO-1.38-416.el8.x86_64
perl-Time-Local-1.280-1.el8.noarch
perl-File-Temp-0.230.600-1.el8.noarch
perl-TimeDate-2.30-13.el8.noarch
perl-Digest-MD5-2.55-396.el8.x86_64
perl-Storable-3.11-3.el8.x86_64
perl-IPC-Run-0.99-1.el8.noarch
perl-TermReadKey-2.37-7.el8.x86_64
perl-Term-Cap-1.17-395.el8.noarch
perl-Mozilla-CA-20160104-7.el8.noarch
perl-Pod-Simple-3.35-395.el8.noarch
perl-podlators-4.11-1.el8.noarch
perl-Pod-Perldoc-3.28-396.el8.noarch
perl-IO-Socket-SSL-2.066-3.el8.noarch
perl-URI-1.73-3.el8.noarch
perl-Carp-1.42-396.el8.noarch
perl-macros-5.26.3-416.el8.x86_64
perl-File-Path-2.15-2.el8.noarch
perl-threads-2.21-2.el8.x86_64
perl-MIME-Base64-3.15-396.el8.x86_64
perl-Data-Dumper-2.167-399.el8.x86_64
perl-Net-SSLeay-1.88-1.el8.x86_64
perl-Error-0.17025-2.el8.noarch
perl-Time-Duration-1.21-3.el8.noarch
perl-Getopt-Long-2.50-4.el8.noarch
perl-HTTP-Tiny-0.074-1.el8.noarch
perl-Git-2.18.1-4.el8.noarch
```

Any help is appreciated

**Comment by smxi** [comment]
This is a glitch caused by my running 5.028 on all my systems, sorry about that, acxi of course is supposed to work on any system back to 5.010.

https://www.effectiveperlprogramming.com/2018/08/initialize-array-and-hash-variables-with-state/

> Perl v5.28 allows you to initialize array and hash variables that you declare with state. This is a feature a long time coming and that I’m quite happy as finally arrived.
> 
> Since v5.10 and up to v5.26 you could only initialize a state variable if it was a scalar. You could declare a hash or array variable but you couldn’t give it an initial value at the same time.

This bug was introduced in a recent update designed to get rid of errors when trying to read unreadable directories, I had in fact initialized the state array:

`state @pruned = ();`

just out of habit and the problem did not show itself since my systems as noted are running perl 5.028.

Thanks for bringing this fairly serious oversight to my attention, it's been fixed in master and as soon as you confirm the fix fixed it, I'll rush out a new release since this issue will make acxi inoperable for all systems not running 5.028 or newer.

**Comment by smxi** [comment]
By the way, thanks for checking acxi out, and taking the time to report the bug. acxi is my personal favorite since I use it so much.

**Comment by soerenschneider** [comment]
Wow, that was fast! Thanks, I can confirm the fix - it's working on CentOS 8 now! 
Thanks for the explanation, Perl's rather exotic for me so I couldn't really help myself. 

Now that it's working I'll check acxi out tomorrow - it appears to be a good fit for my use-case!

**Comment by smxi** [comment]
It wasn't my first guess, but the error message was so clear it made it pretty easy to figure it out. The line number threw me off since it didn't match, but since you posted the full error message (always a good idea) it was easy to figure out, particularly since I just added that feature.

I've been doing a lot of work on acxi because I'm using it to redo a really big collection of flacs. Big hint: opus has full native import support for embedded images in flacs, ogg does not. I've also just switched my lossy synced collection to opus from ogg.

What is your use case out of curiosity? Mine has expanded massively with acxi's new tagging etc features.
